### ISSUE TITLE
o.g.b:command-security-maven-plugin:1.0.11 not available in maven-central

### ISSUE THREAD

**Issue by pzygielo** [eclipse-ee4j/glassfish-security-plugin#12]
Can [1.0.11](https://github.com/eclipse-ee4j/glassfish-security-plugin/releases/tag/1.0.11) be promoted to central from staging?

**Comment by arjantijms** [comment]
This appeared not to be super trivial as many glassfish repos are mapped to the same project, causing rc-list to become confused somehow (mixing-up repos/namespaces), but here it is:

https://repo1.maven.org/maven2/org/glassfish/build/command-security-maven-plugin/1.0.11/

**Comment by pzygielo** [comment]
Thanks!
