### ISSUE TITLE
releasing new glassfish security plugin

### ISSUE THREAD

**Issue by rlfnb** [eclipse-ee4j/glassfish-security-plugin#9]
updating the asm lib to 7.1 needs a new release to make the change effective. Who can do the release?
TIA,
rlfnb

**Comment by rlfnb** [comment]
`
z230-1:~/workspace$ git clone git@github.com:eclipse-ee4j/glassfish-security-plugin.git
Cloning into 'glassfish-security-plugin'...
remote: Enumerating objects: 37, done.
remote: Counting objects: 100% (37/37), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 37 (delta 8), reused 37 (delta 8), pack-reused 0
Receiving objects: 100% (37/37), 49.14 KiB | 7.02 MiB/s, done.
Resolving deltas: 100% (8/8), done.
z230-1:~/workspace$ cd glassfish-security-plugin/
z230-1:~/workspace/glassfish-security-plugin$ mvn clean package
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------< org.glassfish.build:command-security-maven-plugin >----------
[INFO] Building Command Security Plug-in 1.0.10-SNAPSHOT
[INFO] ----------------------------[ maven-plugin ]----------------------------
[WARNING] The POM for org.ow2.asm:asm-all:jar:7.1 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.321 s
[INFO] Finished at: 2019-04-27T12:49:41+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project command-security-maven-plugin: Could not resolve dependencies for project org.glassfish.build:command-security-maven-plugin:maven-plugin:1.0.10-SNAPSHOT: Failure to find org.ow2.asm:asm-all:jar:7.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
z230-1:~/workspace/glassfish-security-plugin$ 
`
any hint, what im doing wrong? Did not find the asm-all.jar at all in the specified version.

**Comment by rlfnb** [comment]
@arjantijms maybe you can help with building a new release for the plugin? Its the last remaining blocker for building glassfish with java11 and maven 3.5.4 (see https://github.com/eclipse-ee4j/glassfish/issues/22754 ).Would be great to have it fixed :)
TIA,
rlfnb

**Comment by rlfnb** [comment]
I would love to help, but it seems like the plugin is already registered, so a PGP key should already exist to upload a new version of the plugin? Who might help here?

**Comment by smillidge** [comment]
@hs536 as a committer you should be able to release this
